version: "3"
services:
  core-scraper:
    build: .
    container_name: "core-scraper"
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports: 
      - "8000:8000"
    volumes: 
      - ./app:/app 
    cap_add:
      - SYS_ADMIN
      
  # redis-overcommit-on-host
  redis-overcommit:
    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    restart: 'no'
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm

  # Your existing Redis service
  redis:
    image: 'redis'
    restart: 'always'
    depends_on:
      - redis-overcommit
